DROP DATABASE IF EXISTS BD_Blog;

CREATE DATABASE IF NOT EXISTS BD_Blog;
-- CHARACTER SET utf8mb4;
USE BD_Blog;

CREATE TABLE rols(
  Id INT AUTO_INCREMENT,
  Name varchar(250) UNIQUE,

  PRIMARY KEY(Id)
  );

CREATE TABLE IF NOT EXISTS Users (
  Id INT AUTO_INCREMENT,
  Email VARCHAR(250) UNIQUE,
  Name VARCHAR(250) UNIQUE,
  Password VARCHAR(250),
  Creation DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS Post (
  Id INT AUTO_INCREMENT,
  Creation DATETIME DEFAULT CURRENT_TIMESTAMP,
  Publish_at DATETIME,
  AuthorId INT,
  Content TEXT,
  Image VARCHAR(250),
  PRIMARY KEY (Id),
  FOREIGN KEY (AuthorId) REFERENCES Users(Id)
);
